static char *create_enum(void)
{
  char *output = NULL;
  char tmp[1024];
  int n;

  output = __calloc(4096, sizeof(char));

  strncpy(output, "/* **WARNING** DO NOT EDIT THIS FILE! THIS FILE WAS GENERATED BY THE BUILD. */\n#ifndef X_SYNTAX_FACTS_H\n#define X_SYNTAX_FACTS_H\n\n", 131);

  strncat(output, "enum\n{\n", 8);
  for (uint64_t i = 0; i < definitions_buffer_size; i++)
  {
    memset(tmp, 0, 1024 * sizeof(char));
    n = sprintf(tmp, "  %s,\n", definitions_buffer[i]);
    strncat(output, tmp, n);
  }
  strncat(output, "};\n\n", 5);

  strncat(output, "enum\n{\n", 8);
  for (uint64_t i = 0; i < returns_buffer_size; i++)
  {
    memset(tmp, 0, 1024 * sizeof(char));
    n = sprintf(tmp, "  %s,\n", returns_buffer[i]);
    strncat(output, tmp, n);
  }
  strncat(output, "};\n\n", 5);

  strncat(output, "#endif/*X_SYNTAX_FACTS_H*/\n", 28);

  buffer_destroy();

  definitions_buffer = NULL;
  definitions_buffer_size = 0;

  returns_buffer = NULL;
  returns_buffer_size = 0;

  return output;
}
